.TH DWM 1 dwm\-VERSION
.SH NAME
dwm \- dynamic window manager (Ryan's build)
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
dwm is a dynamic window manager for X.
.P
dwm "orders" windows based on recency and primacy, while dwm layouts may
change, the most recent "master" window is shown in the most prominent
position. There are bindings for cycling through and promoting windows to the
master position.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
Each screen contains a small status bar which displays all available tags, the
layout, the title of the focused window, and the text read from the root window
name property, if the screen is focused. A floating window is indicated with an
empty square and a maximised floating window is indicated with a filled square
before the windows title.  The selected tags are indicated with a different
color. The tags of the focused window are indicated with a filled square in the
top left corner.  The tags which are applied to one or more windows are
indicated with an empty square in the top left corner.
.P
dwm draws a small border around windows to indicate the focus state.
.P
.I
libxft-bgra
should be installed for this build of dwm. Arch users may install it via the
AUR. Color characters and emoji are enabled, but these will cause crashes
without the fix
.I
libxft-bgra
offers.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE
.SS Status bar
.TP
.B X root window name
is read and displayed in the status text area. It can be set with the
.BR xsetroot (1)
command.
.TP
.B Left click
click on a tag label to display all windows with that tag, click on the layout
label toggles between tiled and floating layout.
.TP
.B Right click
click on a tag label adds/removes all windows with that tag to/from the view.
.TP
.B Super\-Left click
click on a tag label applies that tag to the focused window.
.TP
.B Super\-Right click
click on a tag label adds/removes that tag to/from the focused window.
.SS Keyboard commands
.TP
.B Super\-Return
Start terminal,
.BR st(1).
.TP
.B Super\-d
Spawn application launcher.
.TP
.B Super\-Shift\-d
Spawn command launcher.
.TP
.B Super\-b
Toggles bar on and off.
.TP
.B Super\-q
Close focused window.
.TP
.B Super\-t
Sets tiled layout.
.TP
.B Super\-Shift\-t
Sets bstack layout.
.TP
.B Super\-f
Toggle fullscreen window.
.TP
.B Super\-Shift\-f
Toggle floating layout.
.TP
.B Super\-y
Launch FreeTube.
.TP
.B Super\-space
Zooms/cycles focused window to/from master area.
.TP
.B Super\-j/k
Focus next/previous window.
.TP
.B Super\-Shift\-j/k
Move selected window down/up in stack.
.TP
.B Super\-h
Decrease master area size.
.TP
.B Super\-l
Increase master area size.
.TP
.B Super\-Shift\-space
Toggle focused window between tiled and floating state.
.TP
.B Super\-Tab
Toggles to the previously selected tags.
.TP
.B Super\-g
Moves to the previous tag.
.TP
.B Super\-Shift\-g
Moves selected window to the previous tag.
.TP
.B Super\-semicolon
Moves to the next tag.
.TP
.B Super\-Shift\-semicolon
Moves selected window to the next tag.
.TP
.B Super\-Page_Up
Moves to the previous tag.
.TP
.B Super\-Shift\-Page_Up
Moves selected window to the previous tag.
.TP
.B Super\-Page_Down
Moves to the next tag.
.TP
.B Super\-Shift\-Page_Down
Moves selected window to the next tag.
.TP
.B Super\-a
Toggle gaps.
.TP
.B Super\-Shift\-a
Reset gaps to default.
.TP
.B Super\-z
Increase gaps between windows.
.TP
.B Super\-x
Decrease gaps between windows.
.TP
.B Super\-Shift\-[1..7]
Apply nth tag to focused window.
.TP
.B Super\-Shift\-0
Apply all tags to focused window.
.TP
.B Super\-[1..7]
View all windows with nth tag.
.TP
.B Super\-0
View all windows with any tag.
.TP
.B Super\-BackSpace
Open power menu.
.TP
.B Super\-Print
Start/stop screen recording.
.TP
.B Super\-Shift\-q
Launch system action menu.
.TP
.B Print
Take screenshot with flameshot.
.TP
.B Shift\-Print
OCR (text recognition) from screen.
.SS Common applications
.TP
.B Super\-w
Launch web browser.
.TP
.B Super\-e
Launch Thunderbird email client.
.TP
.B Super\-r
Launch file manager (lfub).
.TP
.B Super\-n
Launch Obsidian.
.TP
.B Super\-s
Launch Spotify.
.TP
.B Super\-c
Launch VS Code.
.TP
.B Super\-v
Launch clipboard menu.
.TP
.B Super\-Shift\-v
Launch Vesktop (Discord).
.SS Mouse commands
.TP
.B Super\-Left click
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B Super\-Middle click
Reset gaps to default.
.TP
.B Super\-Right click
Resize focused window while dragging. Tiled windows will be toggled to the floating state.
.SH CUSTOMIZATION
dwm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SIGNALS
.TP
.B SIGHUP - 1
Restart the dwm process.
.TP
.B SIGTERM - 15
Cleanly terminate the dwm process.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
